- apt: upgrade=dist update_cache=yes

- name: Install HWE
  shell:  apt-get install --install-recommends linux-generic-hwe-18.04 xserver-xorg-hwe-18.04 -y
  args:
    warn: false

- name: accept mscorefonts
  debconf: name='ttf-mscorefonts-installer' question='msttcorefonts/accepted-mscorefonts-eula' value='true' vtype='select'

- name: Install Common APT Packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
  vars:
    packages:
    - htop
    - iotop
    - xauth
    - landscape-common
    - tmux
    - screen
    - imagemagick
    - exfat-utils
    - ntfs-3g
    - dosfstools
    - xfsprogs
    - reiserfsprogs
    - reiser4progs
    - dmraid
    - dmsetup
    - kpartx
    - cryptsetup
    - openssh-server
    - parallel
    - quota
    - nmap
    - lrzip
    - p7zip-full
    - unace
    - unrar
    - zip
    - unzip
    - sharutils
    - rar
    - uudeview
    - mpack
    - arj
    - cabextract
    - gdebi-core
    - dkms
    - ubuntu-restricted-addons
    - ubuntu-restricted-extras
    - ansible
    - apparmor-profiles-extra
    - apparmor-profiles
    - smartmontools
    - squashfs-tools
    - singularity-container
    - links2
    - aptitude
    - tree
    - unattended-upgrades
    - nvme-cli
    - denyhosts
#Development software
    - vim
    - emacs
    - build-essential
    - source-highlight
    - cmake
    - cmake-curses-gui
    - gcc
    - gfortran
    - openjdk-8-jdk
    - git
    - make
    - cpanminus
#Science software
    - environment-modules
    - octave
#Docker
    - docker-ce
    - docker-ce-cli
    - containerd.io
#minc-toolkit-v2 build deps
    - bc
    - bison
    - flex
    - libx11-dev
    - x11proto-core-dev
    - libxi6
    - libxi-dev
    - libxmu6
    - libxmu-dev
    - libxmu-headers
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libjpeg-dev
    - libssl-dev
    - zlib1g-dev
    - automake
#mrtrix3 dependencies
    - python
    - python-numpy
    - libeigen3-dev
    - zlib1g-dev
    - libqt4-opengl-dev
    - libgl1-mesa-dev
    - libfftw3-dev
    - libtiff5-dev
#afni dependencies
    - tcsh
    - xfonts-base
    - python-qt4
    - gsl-bin
    - netpbm
    - libjpeg62
    - xvfb
    - libglu1-mesa-dev
    - libglw1-mesa
    - libxm4
    - libcurl4-openssl-dev
    - libxml2-dev
    - libssl-dev
    - libgfortran3

- name: Install missing libpng package for rstudio and itksnap
  apt:
    deb: http://security.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1.1_amd64.deb

#Fix afni being built against a different version of gsl
#https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu18.html
- name: fix libgsl
  file:
    src: /usr/lib/x86_64-linux-gnu/libgsl.so.23
    dest: /usr/lib/x86_64-linux-gnu/libgsl.so.19
    state: link

- cpanm: name="Math::Matrix"

- name: Install x2go session
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 3600
    install_recommends: no
    autoclean: yes
    autoremove: yes
  vars:
    packages:
      - lxde-core

- name: Install workstation apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  vars:
    packages:
      - gle-graphics
      - texlive-full
      - imagej
      - language-pack-en
      - language-pack-fr
      - language-pack-de
      - feh
      - xfig
      - meshlab
      - google-chrome-stable
      - hunspell-en-ca
      - hunspell-en-gb
      - hunspell-en-med
      - hunspell-fr
      - libreoffice
      - inkscape
      - gimp
      - vlc
